lr: 0.001
weight_decay: 1.0e-03
use_ema: False
ema_momentum: 0.9999
seed: 1234
input_shape:
- 512
- 512
- 3
loss_weights:
  - 0.5
  - 5
threshold_metric: 0.25
gradient_clip_value: 1
batch_size: 4
epochs: 50
train_path: 
- "/content/train"
test_path:
- "/content/hold"
checkpoint_path: "/content/drive/MyDrive/xview2_checkpoint2/unet_trans"
step_warmup: 4000
unet :
  target: model.unet.TransUNet_AutoEncoder
  params:
    hidden_sizes:
      - 64
      - 128
      - 320
      - 512
    unet_num_res_blocks: 2
    unet_num_heads: 8
    unet_num_transformer: 4
    depths:
      - 2
      - 2
      - 2
      - 2
    drop_path_rate: 0.1
      