model:
  learning_rate: 0.0001
  epochs: 70
  seed: 1234
  target: model.model.build_model
  checkpoint_path: "/content/drive/MyDrive/xview2_checkpoint2/usegformer2/"
  params:
    shape_input: 
    - 3
    - 512
    - 512
    pretrainedsegformer: "nvidia/segformer-b3-finetuned-ade-512-512"
 
data:
  train:
    target: model.data.dataloader.DataGen
    params:
      path_list:
      - "/content/train"
      - "/content/tier3"
      batch_size: 4
      img_size : 512
      augmentation : True
  test:
    target: model.data.dataloader.EvalGen
    params:
      path_list:
      - "/content/hold"
