lr: 0.001
weight_decay: 1.0e-04
use_ema: False
ema_momentum: 0.9999
seed: 1234
input_shape:
- 512
- 512
- 3
threshold_metric: 0.25
gradient_clip_value: 1
batch_size: 4
epochs: 50
train_path: 
- "/content/train"
test_path:
- "/content/hold"
checkpoint_path: "/content/drive/MyDrive/xview2_checkpoint2/usegformer"
step_warmup: 4000
loss_weights:
  - 1
  - 11
weights:
  - 0.1
  - 0.1
  - 0.3
  - 0.3
  - 0.2
unet_checkpoint_path: "/content/drive/MyDrive/xview2_checkpoint2/unet_trans"
unet_config_path: "/content/drive/MyDrive/xview2_checkpoint2/unet_trans/config.yaml"
usegformer :
  target: model.usegformer.build_uspatialcondition_model
  params:
    input_shape:
      - 512
      - 512
      - 3
    context_shape:
      - 512
      - 512
      - 1
    widths:
      - 16
      - 32
      - 64
      - 128
      - 320
      - 512
    num_attention_heads:
      - 1
      - 1
      - 1
      - 2
      - 5
      - 8
    strides:
      - 4
      - 4
      - 4
      - 8
      - 16
      - 32
    sr_ratios:
      - 8
      - 8
      - 8
      - 4
      - 2
      - 1
    patch_sizes:
      - 16
      - 8
      - 8
      - 8
      - 4
      - 4
    has_attention:
      - False
      - False
      - True
      - True
      - True
      - True
      