model:
  learning_rate: 0.0001
  epochs: 70
  target: model.model.build_modelv2
  checkpoint_path: "/content/drive/MyDrive/xview2_checkpoint2/usegformer2_v2/"
  params:
    shape_input: 
    - 3
    - 512
    - 512
    pretrainedsegformer: "nvidia/segformer-b3-finetuned-ade-512-512"

seed: 1234

data:
  train:
    target: data.dataloader.DataGen
    params:
      path_list:
      - "/content/train"
      - "/content/tier3"
      batch_size: 4
      img_size : 512
      augmentation : True
  test:
    target: data.dataloader.EvalGen
    params:
      path_list:
      - "/content/hold"
  test_local:
    target: data.dataloader.EvalUnetGen
    params:
      path_list:
      - "/content/hold"
